id: {
    status_active: "Aktif Berkreasi",
    brand_core: "BRAND CORE",
    local_time: "WAKTU LOKAL (INDONESIA)",
    base_on: "BASE ON",
    established: "ESTABLISHED",
    social_title: "Hubungkan & Ikuti",
    social_badge: "Official Links",
    whatsapp_channel: "Saluran WhatsApp",
    project_kicker: "PROJECT UNGGULAN",
    project_link: "Lihat Repository",
    project_description: "Perangkat lirik karaoke pintar untuk modul LCD 16×2 dengan dashboard kontrol Wi-Fi, 20 model sinkronisasi lirik, dan 20 preset animasi transisi mulus.",
    upcoming_kicker: "PROYEK MENDATANG",
    upcoming_title: "Project Codename: Horizon-X (ESP32)",
    upcoming_description: "Proyek perangkat keras eksperimental bertenaga ESP32 sedang dalam tahap riset dan perakitan rahasia. Detail fitur, skema sirkuit, dan cara kerja sistem saat ini masih dirahsiakan hingga peluncuran resmi.",
    support_heading: "Dukung Terus Karya Kreatif",
    support_para: "Dukungan Anda sangat berarti untuk membiayai komponen hardware, pengembangan sistem, dan riset proyek open-source selanjutnya.",
    copyright: "© A.H 5.1 · All Rights Reserved",
    decrypt_btn: "Buka Kunci Preview R&D"
  },
  en: {
    status_active: "Actively Creating",
    brand_core: "BRAND CORE",
    local_time: "LOCAL TIME (INDONESIA)",
    base_on: "BASE ON",
    established: "ESTABLISHED",
    social_title: "Connect & Follow",
    social_badge: "Official Links",
    whatsapp_channel: "WhatsApp Channel",
    project_kicker: "FEATURED PROJECT",
    project_link: "View Repository",
    project_description: "Smart karaoke lyric display for LCD 16×2 with Wi-Fi dashboard, 20 sync models, and 20 smooth transition presets.",
    upcoming_kicker: "UPCOMING PROJECT",
    upcoming_title: "Project Codename: Horizon-X (ESP32)",
    upcoming_description: "An experimental ESP32-powered hardware project currently in confidential research and fabrication. Circuit schematics, features, and system internals remain classified until official release.",
    support_heading: "Support Creative Innovations",
    support_para: "Your support fuels hardware components, embedded system development, and future open-source projects.",
    copyright: "© A.H 5.1 · All Rights Reserved",
    decrypt_btn: "Unlock R&D Preview"
  },
  ms: {
    status_active: "Aktif Berkarya",
    brand_core: "TERAS JENAMA",
    local_time: "WAKTU TEMPATAN (INDONESIA)",
    base_on: "PANGKALAN",
    established: "DITUBUHKAN",
    social_title: "Sambung & Ikuti",
    social_badge: "Pautan Rasmi",
    whatsapp_channel: "Saluran WhatsApp",
    project_kicker: "PROJEK UTAMA",
    project_link: "Lihat Repositori",
    project_description: "Peranti lirik karaoke pintar untuk modul LCD 16×2 dengan papan pemuka Wi-Fi, 20 model penyelarasan lirik, dan 20 animasi lancar.",
    upcoming_kicker: "PROJEK AKAN DATANG",
    upcoming_title: "Project Codename: Horizon-X (ESP32)",
    upcoming_description: "Projek perkakasan eksperimental berkuasa ESP32 sedang dalam fasa penyelidikan rahsia. Skema litar, ciri-ciri, dan cara kerja sistem masih dirahsiakan sehingga pelancaran rasmi.",
    support_heading: "Sokong Terus Karya Kreatif",
    support_para: "Sokongan anda amat bermakna untuk komponen perkakasan, pembangunan sistem, dan penyelidikan projek sumber terbuka.",
    copyright: "© A.H 5.1 · Hak Cipta Terpelihara",
    decrypt_btn: "Nyahkunci Pratonton R&D"
  },
  cs: {
    status_active: "Aktivně tvořím",
    brand_core: "JÁDRO ZNAČKY",
    local_time: "MÍSTNÍ ČAS (INDONÉSIE)",
    base_on: "ZÁKLADNA",
    established: "ZALOŽENO",
    social_title: "Připojte se & Sledujte",
    social_badge: "Oficiální odkazy",
    whatsapp_channel: "Kanál WhatsApp",
    project_kicker: "PŘIPRAVOVANÝ PROJEKT",
    project_link: "Zobrazit repozitář",
    project_description: "Chytré karaoke zobrazovací zařízení pro LCD modul 16×2 s ovládacím Wi-Fi panelem, 20 modely synchronizace textu a 20 plynulými přechodovými animacemi.",
    upcoming_kicker: "PŘIPRAVOVANÝ PROJEKT",
    upcoming_title: "Project Codename: Horizon-X (ESP32)",
    upcoming_description: "Experimentální hardwarový projekt založený na ESP32 je v současné době ve fázi utajeného výzkumu a výroby. Schémata zapojení, funkce a vnitřní fungování systému zůstávají až do oficiálního představení utajeny.",
    support_heading: "Podpořte kreativní vývoj",
    support_para: "Vaše podpora přímo financuje nákup hardwarových komponentů, vývoj vestavěných systémů a budoucí open-source projekty.",
    copyright: "© A.H 5.1 · Všechna práva vyhrazena",
    decrypt_btn: "Odemknout náhled R&D"
  }
